[package]
name = "git-jira-tools"
version = "0.1.0"
authors = ["Eunchong Yu <kroisse@gmail.com>"]

[[bin]]
name = "git-jira"
path = "src/bin.rs"

[dependencies]
log = "*"
hyper = ">=0.5.2"
regex = "*"
rustc-serialize = "*"
